Vagrant.configure("2") do |config|

  config.vm.box = "gozma14/wp"
  config.vm.hostname = "gaboo-plugins"
  config.vm.network "private_network", ip: "192.168.27.14"
  config.vm.synced_folder "..", "/vagrant"

  ###############################################################
  # gaboo synced folders
  ###############################################################

  config.vm.synced_folder "../gaboo/gaboo", "/var/www/www.192.168.27.14.xip.io/public_html/wp-content/plugins/gaboo"
  config.vm.synced_folder "../gaboo/gaboo-core", "/var/www/www.192.168.27.14.xip.io/public_html/wp-content/plugins/gaboo-core"
  config.vm.synced_folder "../gaboo/gaboo-lock", "/var/www/www.192.168.27.14.xip.io/public_html/wp-content/plugins/gaboo-lock"
  config.vm.synced_folder "../gaboo/gaboo-piwik", "/var/www/www.192.168.27.14.xip.io/public_html/wp-content/plugins/gaboo-piwik"

  ###############################################################
  # gaboo-types synced folders
  ###############################################################

  config.vm.synced_folder "../gaboo-types", "/var/www/www.192.168.27.14.xip.io/public_html/wp-content/plugins/gaboo-types"

  ###############################################################
  # gaboo-types-niches synced folders
  ###############################################################

  config.vm.synced_folder "../gaboo-types-niches/gaboo-bells", "/var/www/www.192.168.27.14.xip.io/public_html/wp-content/plugins/gaboo-types-bells"
  config.vm.synced_folder "../gaboo-types-niches/gaboo-book-library", "/var/www/www.192.168.27.14.xip.io/public_html/wp-content/plugins/gaboo-types-book-library"
  config.vm.synced_folder "../gaboo-types-niches/gaboo-portfolio", "/var/www/www.192.168.27.14.xip.io/public_html/wp-content/plugins/gaboo-types-portfolio"
  config.vm.synced_folder "../gaboo-types-niches/gaboo-real-estate", "/var/www/www.192.168.27.14.xip.io/public_html/wp-content/plugins/gaboo-types-real-estate"
  config.vm.synced_folder "../gaboo-types-niches/gaboo-restaurant", "/var/www/www.192.168.27.14.xip.io/public_html/wp-content/plugins/gaboo-types-restaurant"
  config.vm.synced_folder "../gaboo-types-niches/gaboo-testimonials", "/var/www/www.192.168.27.14.xip.io/public_html/wp-content/plugins/gaboo-types-testimonials"
  config.vm.synced_folder "../gaboo-types-niches/gaboo-whistles", "/var/www/www.192.168.27.14.xip.io/public_html/wp-content/plugins/gaboo-types-whistles"

  ###############################################################
  # cli/provision
  ###############################################################

  config.vm.provision "shell", path: "cli/provision.sh", privileged: false

end